name: Probando minimal R

on:
    workflow_dispatch: # Permitir la ejecución manual

jobs:
    ejecutar-script:
        runs-on: ubuntu-20.04

        container:
            image: rhub/r-minimal:latest
            options: --entrypoint /bin/sh # Especificar sh como el entrypoint si está disponible

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Cache system dependencies
              uses: actions/cache@v2
              with:
                  path: /var/cache/apk
                  key: ${{ runner.os }}-apk-${{ hashFiles('**/apk/*.list') }}
                  restore-keys: |
                      ${{ runner.os }}-apk-

            - name: Instalar dependencias del sistema
              run: |
                  apk add --no-cache --virtual .rdeps gcc g++ gfortran musl-dev

            - name: Instalar R y paquetes adicionales
              run: |
                  installr -d -t "curl-dev" -a "curl-dev" googlesheets4 googledrive httr jsonlite base64enc curl

            - name: Create credentials file
              run: |
                  echo '${{ secrets.OAUTH_TOKEN }}' > credentials.json

            - name: Autenticar y ejecutar script R
              env:
                  GDRIVE_TOKEN: ${{ secrets.OAUTH_TOKEN }}
                  IMPORTACIONES_URL: ${{ secrets.IMPORTACIONES_URL }}
                  CREDENCIALES_URL: ${{ secrets.CREDENCIALES_URL }}
              run: |
                  Rscript update_sheets.R
